version: 2
updates:
  - package-ecosystem: 'gradle'
    directories:
      - 'pdc-keycloak-theme'
      - 'twilio-keycloak-provider'
      - 'keycloak-required-action'
    schedule:
      interval: 'daily'
    groups:
      junit-jupiter:
        patterns:
          - 'org.junit.*'
          - 'org.mockito.*jupiter*'
  - package-ecosystem: 'github-actions'
    directory: '.github/workflows'
    schedule:
      interval: 'daily'
