name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  target_node:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v3
      - name: Get Zulu OpenJDK (current LTS version).
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build a shaded fat jar.
        working-directory: twilio-keycloak-provider
        run: ./gradlew shadowJar
